package com.petwellness.model.enums;

public enum InstitucionEducativa {
    // Universidades en Perú
    UNIVERSIDAD_NACIONAL_MAYOR_DE_SAN_MARCOS,
    UNIVERSIDAD_CIENTIFICA_DEL_SUR,
    UNIVERSIDAD_NACIONAL_HERMILIO_VALDIZAN,
    UNIVERSIDAD_NACIONAL_DE_SAN_ANTONIO_ABAD_DEL_CUSCO,
    UNIVERSIDAD_NACIONAL_DE_TRUJILLO,
    UNIVERSIDAD_PERUANA_CAYETANO_HEREDIA,

    // Universidades Internacionales
    CORNELL_UNIVERSITY, // USA
    UNIVERSITY_OF_CAMBRIDGE, // Reino Unido
    UNIVERSITY_OF_MELBOURNE, // Australia
    UNIVERSITY_OF_SYDNEY, // Australia
    UNIVERSITY_OF_GLASGOW, // Reino Unido
    UNIVERSITY_OF_EDINBURGH, // Reino Unido
    UNIVERSITY_OF_CALIFORNIA_DAVIS, // USA
    UNIVERSITY_OF_PRETORIA, // Sudáfrica
    UNIVERSITY_OF_GUELPH // Canadá
}
